language: python
python:
  - 3.5
  - 3.6
# <Workaround>. Python 3.7 not yet supported on Travis
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
# </Workaround>
install:
    - "python setup.py install"
    - "pip install -r dev_requirements.txt"
script: pytest
